server:
  port: 80

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

